mshv-bindings: Turn off default features for num_enum
num_enum with default features turned breaks the compilation of
rust-vmm/vfio crate.

error: package `toml_edit v0.21.1` cannot be built because it requires rustc 1.69 or newer, while the currently active rustc version is 1.67.1
Either upgrade to rustc 1.69 or newer, or use
cargo update -p toml_edit@0.21.1 --precise ver
where `ver` is the latest version of `toml_edit` supporting rustc 1.67.1
🚨 Error: The command exited with status 101

Signed-off-by: Jinank Jain <jinankjain@microsoft.com>